import type { Page } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { expect, test } from '@nuxt/test-utils/playwright'

test.use({ nuxt: { rootDir: fileURLToPath(new URL('../fixtures/adaptive-select', import.meta.url)) } })

function collectIssues(page: Page) {
  const issues: string[] = []
  page.on('pageerror', (error: Error) => issues.push(error.message))
  page.on('console', (message: { text: () => string }) => {
    if (/hydration|mismatch/i.test(message.text()))
      issues.push(message.text())
  })
  return issues
}

test('owns mobile Select focus through filtering, Tab, selection and native submission', async ({ page, goto }) => {
  const issues = collectIssues(page)
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/', { waitUntil: 'hydration' })
  const trigger = page.locator('#select-trigger')
  await expect(trigger).toHaveAttribute('aria-haspopup', 'dialog')
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Choose a number', exact: true })
  const input = dialog.getByRole('combobox', { name: 'Search...', exact: true })
  await expect(input).toBeFocused()
  await expect(dialog).toHaveAttribute('aria-modal', 'true')
  await expect(trigger).toHaveAttribute('aria-controls', await dialog.getAttribute('id') as string)
  await input.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await input.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  await input.click()
  await input.fill('Tw')
  await expect(dialog.getByRole('option', { name: 'One', exact: true })).toHaveCount(0)
  await input.dispatchEvent('compositionstart', { data: '' })
  await input.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true, bubbles: true })
  await expect(page.locator('#value-proposals')).toHaveText('[]')
  await expect(dialog).toBeVisible()
  await input.dispatchEvent('compositionend', { data: 'Tw' })
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(page.locator('#value-proposals')).toHaveText('[2]')
  await expect.poll(() => page.locator('#selection-form').evaluate(el => new FormData(el as HTMLFormElement).getAll('choice'))).toEqual(['2'])
  expect(issues).toEqual([])
})

test('preserves controlled empty selection and open veto in an initially open modal', async ({ page, goto }) => {
  const issues = collectIssues(page)
  await page.setViewportSize({ width: 600, height: 800 })
  const path = '/?initial=true&ownership=controlled&model=controlled&veto=true&reject=true'
  const response = await page.request.get(path)
  expect((await response.text())).toContain('id="select-trigger"')
  await goto(path, { waitUntil: 'hydration' })
  const dialog = page.getByRole('dialog', { name: 'Choose a number', exact: true })
  const input = dialog.getByRole('combobox')
  await expect(input).toBeFocused()
  await expect(page.locator('#open-requests')).toHaveText('[]')
  await dialog.getByRole('option', { name: 'Two', exact: true }).click()
  await expect(page.locator('#value-proposals')).toHaveText('[2]')
  await expect(dialog.getByRole('option', { name: 'Two', exact: true })).toHaveAttribute('aria-selected', 'false')
  await expect(dialog).toBeVisible()
  await input.press('Escape')
  await expect(page.locator('#open-requests')).toHaveText('[false,false]')
  await expect(dialog).toBeVisible()
  await expect(input).toBeFocused()
  await page.locator('#allow-close').evaluate(el => (el as HTMLButtonElement).click())
  await input.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(page.locator('#select-trigger')).toBeFocused()
  expect(issues).toEqual([])
})

test('keeps modal multiple selections across filtering and resets the persistent native control', async ({ page, goto }) => {
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/?multiple=true&initial=true', { waitUntil: 'hydration' })
  const dialog = page.getByRole('dialog', { name: 'Choose a number', exact: true })
  const input = dialog.getByRole('combobox')
  await expect(input).toBeFocused()
  await input.fill('Tw')
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(dialog).toBeVisible()
  await input.fill('On')
  await dialog.getByRole('option', { name: 'One', exact: true }).click()
  const values = () => page.locator('#selection-form').evaluate(el => new FormData(el as HTMLFormElement).getAll('choice'))
  await expect.poll(values).toEqual(['2', '1'])
  await expect.poll(() => dialog.getByRole('option', { name: 'One', exact: true }).locator('[data-test="selection-indicator"]').evaluate(el => getComputedStyle(el).color)).toBe('rgb(11, 34, 51)')
  await dialog.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.locator('#select-trigger')).toBeFocused()
  await page.getByRole('button', { name: 'Reset selection', exact: true }).click()
  await expect.poll(values).toEqual([])
})

for (const query of ['searchable=false', 'virtual=true']) {
  test(`uses the modal selection owner with ${query}`, async ({ page, goto }) => {
    const issues = collectIssues(page)
    await page.setViewportSize({ width: 600, height: 800 })
    await goto(`/?initial=true&${query}`, { waitUntil: 'hydration' })
    const dialog = page.getByRole('dialog', { name: 'Choose a number', exact: true })
    await expect.poll(() => page.evaluate(() => !!document.activeElement?.closest('[role="dialog"]'))).toBe(true)
    await page.keyboard.press('Tab')
    await expect(dialog).toBeVisible()
    await expect.poll(() => page.evaluate(() => !!document.activeElement?.closest('[role="dialog"]'))).toBe(true)
    await dialog.getByRole('option', { name: 'Two', exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(page.locator('#select-trigger')).toBeFocused()
    await expect.poll(() => page.locator('#selection-form').evaluate(el => new FormData(el as HTMLFormElement).getAll('choice'))).toEqual(['2'])
    expect(issues).toEqual([])
  })
}
