import type { Page } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { expect, test } from '@nuxt/test-utils/playwright'

test.use({ nuxt: { rootDir: fileURLToPath(new URL('../fixtures/adaptive-autocomplete', import.meta.url)) } })

function collectIssues(page: Page) {
  const issues: string[] = []
  page.on('pageerror', (error: Error) => issues.push(error.message))
  page.on('console', (message: { text: () => string }) => {
    if (/hydration|mismatch/i.test(message.text()))
      issues.push(message.text())
  })
  return issues
}

test('keeps the mobile Autocomplete editor accessible through typing, composition, selection and form submission', async ({ page, goto }) => {
  const issues = collectIssues(page)
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/', { waitUntil: 'hydration' })
  const opener = page.locator('#autocomplete-input')
  await opener.click()
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('combobox')
  await input.fill('Tw')
  const panel = page.locator('[data-test="autocomplete-mobile-panel"]')
  await expect(panel).toBeVisible()
  await expect(dialog).toHaveAttribute('aria-modal', 'true')
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toHaveCount(0)
  await expect(input).toBeFocused()
  await expect(input).toHaveAttribute('aria-expanded', 'true')
  await expect(panel.getByRole('option', { name: 'Two', exact: true })).toBeVisible()
  await input.dispatchEvent('compositionstart', { data: '' })
  await input.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true, bubbles: true })
  await expect(page.locator('#value-proposals')).toHaveText('[]')
  await input.dispatchEvent('compositionend', { data: 'Tw' })
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(page.locator('#value-proposals')).toHaveText('[2]')
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()
  await expect.poll(() => page.locator('#autocomplete-form').evaluate(el => new FormData(el as HTMLFormElement).getAll('number'))).toEqual(['2'])
  await opener.click()
  await expect(input).toBeFocused()
  await input.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()
  expect(issues).toEqual([])
})

test('keeps a controlled mobile Autocomplete modal open when the parent vetoes Escape', async ({ page, goto }) => {
  const issues = collectIssues(page)
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/?initial=true&controlled=true', { waitUntil: 'hydration' })
  const input = page.getByRole('dialog').getByRole('combobox')
  const panel = page.locator('[data-test="autocomplete-mobile-panel"]')
  await expect(panel).toBeVisible()
  await expect(input).toBeFocused()
  await input.press('Escape')
  await expect(page.locator('#open-requests')).toHaveText('[false]')
  await expect(panel).toBeVisible()
  await expect(input).toBeFocused()
  expect(issues).toEqual([])
})

test('commits free text with Enter or Done and resets the native form value', async ({ page, goto }) => {
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/', { waitUntil: 'hydration' })
  const opener = page.locator('#autocomplete-input')
  await opener.click()
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('combobox')
  await input.fill('Custom number')
  await input.press('Enter')
  await expect(dialog).toBeHidden()
  await expect(opener).toHaveValue('Custom number')
  await opener.click()
  await input.fill('Another number')
  await dialog.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(opener).toHaveValue('Another number')
  await expect.poll(() => page.locator('#autocomplete-form').evaluate(el => new FormData(el as HTMLFormElement).getAll('number'))).toEqual(['Another number'])
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(opener).toHaveValue('')
})

for (const query of ['multiple=true&chips=true', 'multiple=true&virtual=true']) {
  test(`preserves suggestions and free-text values with ${query}`, async ({ page, goto }) => {
    await page.setViewportSize({ width: 600, height: 800 })
    await goto(`/?${query}`, { waitUntil: 'hydration' })
    await page.locator('#autocomplete-input').click()
    const dialog = page.getByRole('dialog')
    const input = dialog.getByRole('combobox')
    await input.fill('Tw')
    await dialog.getByRole('option', { name: 'Two', exact: true }).click()
    await expect(dialog).toBeVisible()
    await input.fill('Custom number')
    await input.press('Enter')
    await expect(dialog).toBeVisible()
    await input.fill('Three')
    await dialog.getByRole('option', { name: 'Three', exact: true }).click()
    await dialog.getByRole('button', { name: 'Done', exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(page.locator('#autocomplete-input')).toBeFocused()
    await expect.poll(() => page.locator('#autocomplete-form').evaluate(el => new FormData(el as HTMLFormElement).getAll('number'))).toEqual(['2', 'Custom number', '3'])
  })
}

test('rejects unmatched text with forceSelection and contains keyboard focus', async ({ page, goto }) => {
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/?forced=true', { waitUntil: 'hydration' })
  await page.locator('#autocomplete-input').press('ArrowDown')
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('combobox')
  await expect(input).toBeFocused()
  await input.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Done', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await input.fill('Unknown')
  await input.press('Enter')
  await expect(page.locator('#value-proposals')).toHaveText('[]')
  await expect(dialog).toBeVisible()
  await input.fill('Tw')
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(dialog).toBeHidden()
  await expect(page.locator('#value-proposals')).toHaveText('[2]')
})

test('keeps the open presentation stable across viewport changes', async ({ page, goto }) => {
  await page.setViewportSize({ width: 600, height: 800 })
  await goto('/', { waitUntil: 'hydration' })
  await page.locator('#autocomplete-input').click()
  const dialog = page.getByRole('dialog')
  await page.setViewportSize({ width: 1200, height: 800 })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('combobox').press('Escape')
  await expect(dialog).toBeHidden()
  const desktopInput = page.locator('#autocomplete-input')
  await expect(desktopInput).toBeFocused()
  await desktopInput.fill('Tw')
  await expect(page.getByRole('option', { name: 'Two', exact: true })).toBeVisible()
  await expect(dialog).toHaveCount(0)
  await page.setViewportSize({ width: 600, height: 800 })
  await expect(page.getByRole('option', { name: 'Two', exact: true })).toBeVisible()
  await expect(dialog).toHaveCount(0)
  await desktopInput.press('Escape')
  await page.locator('#autocomplete-input').click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('combobox')).toBeFocused()
})
