import { expect, test } from '@nuxt/test-utils/playwright'

test('keeps forced async numeric selections through hydration, rejection, clearing and reset', async ({ page, goto }) => {
  const issues: string[] = []
  page.on('pageerror', error => issues.push(error.message))
  page.on('console', (message) => {
    if (/hydration|mismatch/i.test(message.text()))
      issues.push(message.text())
  })
  await goto('/', { waitUntil: 'hydration' })
  const form = page.locator('#autocomplete-generic-form')
  const input = form.getByRole('combobox', { name: 'Choose a suggestion', exact: true })
  const values = () => form.evaluate(el => new FormData(el as HTMLFormElement).getAll('forced-choice'))
  await expect(input).toHaveAccessibleDescription('Choose one of the numeric suggestions.')
  await expect(input).toHaveValue('7')
  await expect.poll(values).toEqual(['7'])
  await form.getByRole('button', { name: 'Load suggestions', exact: true }).click()
  await expect(input).toHaveValue('Loaded suggestion')
  await input.fill('Unmatched text')
  await input.press('Enter')
  await expect.poll(values).toEqual(['7'])
  await input.fill('Other unmatched text')
  await form.getByRole('button', { name: 'Load suggestions', exact: true }).click()
  await expect.poll(values).toEqual(['7'])
  await form.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect.poll(values).toEqual([])
  await form.getByRole('button', { name: 'Reset suggestions', exact: true }).click()
  await expect.poll(values).toEqual(['7'])
  await expect(input).toHaveValue('Loaded suggestion')
  expect(issues).toEqual([])
})

test('creates text alongside numeric chips and restores the captured mixed default', async ({ page, goto }) => {
  const issues: string[] = []
  page.on('pageerror', error => issues.push(error.message))
  page.on('console', (message) => {
    if (/hydration|mismatch/i.test(message.text()))
      issues.push(message.text())
  })
  await goto('/', { waitUntil: 'hydration' })
  const form = page.locator('#autocomplete-generic-form')
  const input = form.getByRole('combobox', { name: 'Create suggestions', exact: true })
  const values = () => form.evaluate(el => new FormData(el as HTMLFormElement).getAll('created-choices'))
  await expect.poll(values).toEqual(['0', 'Initial text'])
  await input.fill('Fresh text')
  await input.press('Tab')
  await expect.poll(values).toEqual(['0', 'Initial text', 'Fresh text'])
  await form.getByRole('button', { name: 'Remove Numeric zero', exact: true }).click()
  await expect.poll(values).toEqual(['Initial text', 'Fresh text'])
  await form.getByRole('button', { name: 'Reset suggestions', exact: true }).click()
  await expect.poll(values).toEqual(['0', 'Initial text'])
  await expect(form.getByRole('button', { name: 'Remove Numeric zero', exact: true })).toBeVisible()
  expect(issues).toEqual([])
})
