import { fileURLToPath } from 'node:url'
import { expect, test } from '@nuxt/test-utils/playwright'

test.use({ nuxt: { rootDir: fileURLToPath(new URL('../fixtures/dashboard-resize', import.meta.url)) } })

for (const query of ['', '?dark=true', '?same=true', '?rtl=true']) {
  test(`leaves panel backgrounds and the boundary intact ${query}`, async ({ page, goto }) => {
    await page.setViewportSize({ width: 1200, height: 800 })
    await goto(`/${query}`, { waitUntil: 'hydration' })
    const handle = page.locator('#resize-handle')
    const line = handle.locator('div')
    await expect(handle).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(handle).toHaveCSS('background-image', 'none')
    await expect(page.locator('#panel')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(line).toHaveCSS('opacity', '1')
    await expect.poll(async () => (await page.locator('#sidebar').boundingBox())!.width).toBeCloseTo(260, 0)
    const sidebar = await page.locator('#sidebar').boundingBox()
    const panel = await page.locator('#panel').boundingBox()
    const target = await handle.boundingBox()
    expect(target!.width).toBe(8)
    const boundary = query.includes('rtl') ? sidebar!.x : sidebar!.x + sidebar!.width
    expect(Math.abs((query.includes('rtl') ? panel!.x + panel!.width : panel!.x) - boundary)).toBeLessThan(1)
    expect(Math.abs(target!.x + target!.width / 2 - boundary)).toBeLessThan(1)
    const restingColor = await line.evaluate(element => getComputedStyle(element).backgroundColor)
    await handle.hover()
    await expect(line).toHaveCSS('opacity', '1')
    await expect.poll(() => line.evaluate(element => getComputedStyle(element).backgroundColor)).not.toBe(restingColor)
    const divider = await line.boundingBox()
    expect(Math.abs(divider!.x + divider!.width / 2 - boundary)).toBeLessThan(1)
    await page.mouse.move(1100, 700)
    await expect(line).toHaveCSS('opacity', '1')
    await expect(line).toHaveCSS('background-color', restingColor)
    await page.keyboard.press('Tab')
    await handle.focus()
    await expect(handle).toBeFocused()
    await expect(line).toHaveCSS('opacity', '1')
    await page.keyboard.press('ArrowRight')
    await expect.poll(async () => (await page.locator('#sidebar').boundingBox())!.width).not.toBe(sidebar!.width)
  })
}

test('retains pointer resizing and per-instance overrides', async ({ page, goto }) => {
  await page.setViewportSize({ width: 1200, height: 800 })
  await goto('/?override=true', { waitUntil: 'hydration' })
  const handle = page.locator('#resize-handle')
  await expect(handle).toHaveAttribute('data-custom', 'yes')
  await expect(handle.locator('div')).toHaveCSS('opacity', '0')
  await handle.hover()
  await expect(handle.locator('div')).toHaveCSS('opacity', '1')
  await expect.poll(async () => (await page.locator('#sidebar').boundingBox())!.width).toBeCloseTo(260, 0)
  const sidebar = await page.locator('#sidebar').boundingBox()
  const target = await handle.boundingBox()
  await page.mouse.move(target!.x + 4, target!.y + 100)
  await page.mouse.down()
  await page.mouse.move(target!.x + 64, target!.y + 100)
  await page.mouse.up()
  await expect.poll(async () => (await page.locator('#sidebar').boundingBox())!.width).toBeGreaterThan(sidebar!.width + 40)
  await page.setViewportSize({ width: 600, height: 800 })
  await expect(handle).toHaveCount(0)
})

test('shows the divider throughout dragging even outside its hit area', async ({ page, goto }) => {
  await page.setViewportSize({ width: 1200, height: 800 })
  await goto('/', { waitUntil: 'hydration' })
  const handle = page.locator('#resize-handle')
  await expect.poll(async () => (await page.locator('#sidebar').boundingBox())!.width).toBeCloseTo(260, 0)
  const target = await handle.boundingBox()
  await page.mouse.move(target!.x + 4, target!.y + 100)
  await page.mouse.down()
  await page.mouse.move(500, target!.y + 100)
  await expect(handle).toHaveAttribute('data-state', 'drag')
  await expect(handle.locator('div')).toHaveCSS('opacity', '1')
  await page.mouse.up()
  await expect(handle.locator('div')).toHaveCSS('opacity', '1')
})
