import type { ColorRole } from './color-registry'
// Nuxt creates this virtual module during prepare; the source package's root
// typecheck cannot resolve a consumer-specific #build file before preparation.
// @ts-expect-error generated by the Selaras Nuxt module
import { colorRoles } from '#build/selaras-color-roles.mjs'
import { builtinColorNames } from './color-registry'

const registeredRoles = new Set<string>([...builtinColorNames, ...colorRoles])
const warnedRoles = new Set<string>()

/** Resolves runtime JavaScript role values without emitting unresolved CSS variables. */
export function resolveRegisteredColorRole(role: unknown, fallback: ColorRole): ColorRole {
  if (typeof role !== 'string' || !registeredRoles.has(role)) {
    if (import.meta.dev && typeof role === 'string' && !warnedRoles.has(role)) {
      warnedRoles.add(role)
      console.warn(`[selaras] Unknown color role "${role}". Falling back to "${fallback}".`)
    }
    return fallback
  }
  return role as ColorRole
}
