import type { ComputedRef } from 'vue'
import type { ThemeContext } from './injection-keys'
import { tv } from 'tailwind-variants'
import { computed, inject, mergeProps, useAttrs } from 'vue'
// Virtual module generated by module.ts's setup(), always registered (with
// `classPrefix: null` when the module option is unset) so this import
// never fails to resolve - see module.ts's own addTemplate call.
import { classPrefix as globalClassPrefix } from '#build/selaras-class-prefix.mjs'
import { useAppConfig } from '#imports'
import { THEME_INJECTION_KEY } from './injection-keys'

export type UiSlotValue = string | ({ class?: string } & Record<string, unknown>)
export type UiProp<Slots extends string = string> = Partial<Record<Slots, UiSlotValue>>

/**
 * tailwind-variants' own generated slot-function type is a union of several
 * variant-prop shapes (one per possible variant combination, more of them
 * the fewer variants a theme declares), each intersected with its `ClassProp`
 * union (`{class} | {className}`, never both). No single hand-written object
 * type is structurally assignable to every branch of that union at once, so
 * `resolveSlot`/`useRootProps` are generic over the slot fn's real type
 * instead of pinning it to one - avoiding a wrong-in-every-direction manual
 * approximation (and the `as any` it previously forced on every call site).
 * `any` in this constraint's parameter position is what makes the match
 * trivially succeed regardless of that union's shape; the cast just inside
 * each function body does the same for the one call they each make.
 */
type AnySlotFn = (opts?: any) => string

/**
 * Applies a Tailwind v4 class-prefix (`@import "tailwindcss" prefix(tw);`)
 * to a class string. The prefix always lands as the outermost segment of
 * a class (`tw:hover:bg-red-500`, never `hover:tw:bg-red-500`), so this is
 * a plain per-token prepend - no variant-aware parsing needed. `selaras-*`
 * classes are hand-authored literal selectors (see theme.css), not
 * Tailwind utilities, and must be skipped or they stop matching their own
 * CSS. A token that already starts with `${prefix}:` is left alone too -
 * a consumer's own `:ui` override or custom component can't be covered by
 * Selaras's build-time safelist (module.ts only scans Selaras's own shipped
 * files), so writing it already-prefixed themselves is the documented way
 * to make Tailwind generate CSS for it; without this guard that would get
 * double-prefixed into garbage instead of passing through untouched.
 *
 * `prefix` defaults to the `classPrefix` module option (threaded through
 * via a build-time virtual module, `#build/selaras-class-prefix.mjs` -
 * see module.ts) when omitted, so call sites wrapping a hardcoded literal
 * class (`applyClassPrefix('sr-only')`) don't each need to read it
 * themselves. Pass it explicitly only where the prefix is already in hand
 * (as `resolveSlot` does) or in a unit test.
 *
 * `classString` itself is nullable despite the type: a `tv()` slot with no
 * base classes and no active override (an empty-string slot like
 * Accordion's `header`/`label`) resolves to `undefined`, not `''` - passed
 * straight through here rather than crashing, the same as it would if
 * this function didn't exist at all.
 */
export function applyClassPrefix(classString: string, prefix?: string): string {
  if (!classString)
    return classString
  const resolvedPrefix = prefix ?? globalClassPrefix ?? undefined
  if (!resolvedPrefix)
    return classString
  return classString
    .split(/\s+/)
    .filter(Boolean)
    .map(cls => (cls.startsWith('selaras-') || cls.startsWith(`${resolvedPrefix}:`)) ? cls : `${resolvedPrefix}:${cls}`)
    .join(' ')
}

/**
 * Strips a leading `${prefix}:` from each space-separated token of a class
 * string - the inverse of `applyClassPrefix`'s per-token prepend. `resolveSlot`
 * applies this to a `:ui` override *before* handing it to the slot function,
 * because `tailwind-merge` (bundled by `tailwind-variants`) has no concept
 * of Tailwind v4's `tw:`-style prefix syntax: a mixed merge - an unprefixed
 * base class (`bg-[var(--ui-primary)]`) against an already-prefixed override
 * (`tw:bg-red-500`, exactly what a consumer is documented to write once a
 * prefix is configured) - never dedupes, confirmed directly (both classes
 * survive as-is). Since Selaras's own safelist stylesheet loads after the
 * consumer's own, that would mean Selaras's default silently wins over the
 * consumer's override - the opposite of what `:ui` is for. Normalizing the
 * override back to its unprefixed form before merging (where tailwind-merge
 * already works correctly), then letting `applyClassPrefix` re-prefix the
 * whole merged result afterward, sidesteps this - correct regardless of
 * whether the bundled tailwind-merge version understands `tw:` syntax at all.
 */
export function stripClassPrefix(classString: string | undefined, prefix: string | null | undefined): string | undefined {
  if (!classString || !prefix)
    return classString
  return classString
    .split(/\s+/)
    .filter(Boolean)
    .map(cls => cls.startsWith(`${prefix}:`) ? cls.slice(prefix.length + 1) : cls)
    .join(' ')
}

/**
 * Resolves a single slot's classes/attrs from a `:ui` override.
 * A string override is treated as extra classes (tailwind-merge'd by the slot fn).
 * An object override's `class` is merged the same way, everything else is
 * applied as raw attrs/handlers via `mergeProps` (never tailwind-merged).
 */
export function resolveSlot<T extends AnySlotFn>(slotFn: T, override?: UiSlotValue) {
  const call = slotFn as AnySlotFn
  if (typeof override !== 'object' || override === null) {
    return { class: applyClassPrefix(call({ class: stripClassPrefix(override, globalClassPrefix) })) }
  }
  const { class: overrideClass, ...attrs } = override
  return mergeProps({ class: applyClassPrefix(call({ class: stripClassPrefix(overrideClass, globalClassPrefix) })) }, attrs)
}

/**
 * Vue always merges a parent's fallthrough `class` onto a single-root
 * component's root element via raw string concatenation - completely
 * separate from (and unaware of) the tailwind-merge resolveSlot does. That
 * means a plain `class="w-40"` on a component whose root slot has `w-full`
 * can silently lose depending on Tailwind's generated CSS order, not source
 * order - defeating the whole point of the :ui system.
 *
 * A component styling its root/base slot via resolveSlot should instead set
 * `inheritAttrs: false`, fold the fallthrough class into that slot's :ui
 * override with `withFallthroughClass` so it goes through tailwind-merge too,
 * and bind `attrsWithoutClass` (not raw $attrs) alongside it so every other
 * fallthrough attr still passes through untouched.
 */
export function useRootFallthrough() {
  const attrs = useAttrs()
  const fallthroughClass = computed(() => typeof attrs.class === 'string' ? attrs.class : undefined)
  const attrsWithoutClass = computed(() => {
    const { class: _class, ...rest } = attrs
    return rest
  })
  return { fallthroughClass, attrsWithoutClass }
}

/** Folds a fallthrough class into a slot's `:ui` override, ahead of resolveSlot. */
export function withFallthroughClass(fallthroughClass: string | undefined, override?: UiSlotValue): UiSlotValue | undefined {
  if (typeof override === 'object' && override !== null) {
    return { ...override, class: [fallthroughClass, override.class].filter(Boolean).join(' ') || undefined }
  }
  return [fallthroughClass, override].filter(Boolean).join(' ') || undefined
}

/**
 * Combines resolveSlot with useRootFallthrough for a component's root/base
 * slot in one call - requires `defineOptions({ inheritAttrs: false })` on the
 * component. Bind the result with a single `v-bind` (Vue's template compiler
 * rejects two bare v-bind spreads on the same element).
 */
export function useRootProps<T extends AnySlotFn>(slotFn: () => T, override: () => UiSlotValue | undefined) {
  const { fallthroughClass, attrsWithoutClass } = useRootFallthrough()
  return computed(() => mergeProps(
    attrsWithoutClass.value,
    resolveSlot(slotFn(), withFallthroughClass(fallthroughClass.value, override())),
  ))
}

/**
 * Walks an STheme ancestor chain (see injection-keys.ts's own ThemeContext
 * comment for why `parent` is a back-reference rather than a pre-merged
 * bag) collecting one component key's override - via `pick`, selecting
 * either `.ui` or `.props` - from each ancestor that set it, outermost
 * first - the order useComponentTheme/useThemeProps below need so an
 * inner STheme's override composes on top of (rather than replacing) an
 * outer one's.
 */
function collectThemeChain<V extends object>(context: ThemeContext | undefined, pick: (context: ThemeContext) => Partial<Record<string, V>> | undefined, key: string): V[] {
  const chain: V[] = []
  for (let current = context; current; current = current.parent) {
    const value = pick(current)?.[key]
    if (value)
      chain.unshift(value)
  }
  return chain
}

/**
 * Merges a component's global `app.config.ui.<key>` override, then any
 * ancestor STheme's scoped `ui.<key>` override, into its base `tv()`
 * theme - each layered via tv()'s own `extend` composition, so an
 * override only needs to name the slots it actually changes. Falls back
 * to the base theme untouched when neither exists.
 */
export function useComponentTheme<T extends (...args: any[]) => any>(key: string, base: T): ComputedRef<T> {
  const appConfig = useAppConfig() as { ui?: Record<string, object> }
  const themeContext = inject(THEME_INJECTION_KEY, undefined)

  return computed(() => {
    let result: any = base
    const globalOverride = appConfig.ui?.[key]
    if (globalOverride)
      result = tv({ extend: result, ...globalOverride })
    for (const override of collectThemeChain(themeContext?.value, c => c.ui, key))
      result = tv({ extend: result, ...override })
    return result as T
  })
}

/**
 * The nearest (chain-merged) STheme `props.<key>` override, if any - a
 * component reads this as its own prop's fallback, one level below its
 * own explicit prop but above whatever hardcoded/tv() default it'd
 * otherwise use (`props.size ?? useThemeProps('button').value.size`),
 * mirroring the existing AvatarGroup/FormField "inject a default" precedent
 * generically instead of each needing its own bespoke injection key.
 */
export function useThemeProps(key: string): ComputedRef<Record<string, unknown>> {
  const themeContext = inject(THEME_INJECTION_KEY, undefined)

  return computed(() => Object.assign({}, ...collectThemeChain(themeContext?.value, c => c.props, key)))
}
