name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0

      - uses: actions/setup-node@v7
        with:
          node-version: 24.19.0

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run --bun lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0

      - uses: actions/setup-node@v7
        with:
          node-version: 24.19.0

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: bun install

      - name: Playground prepare
        run: bun run --bun dev:prepare

      - name: Typecheck
        run: bun run --bun test:types

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0

      - uses: actions/setup-node@v7
        with:
          node-version: 24.19.0

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: bun install

      - name: Playground prepare
        run: bun run --bun dev:prepare

      - name: Test
        run: bun run --bun test
